/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import com.google.common.base.Joiner;
import com.google.common.collect.Lists;
import java.util.ArrayList;
import java.util.List;

@SuppressWarnings("java:S106")
public class HelloJava {
    public static void main(String... args) {
        List<Integer> example = new ArrayList<>();
        int min = 0;
        int max = 50;
        for (int i = min; i < max; i++) {
            example.add(i);
        }
        System.out.println("\n" + Lists.reverse(example));
        System.out.print("\n");

        String[] str_my = {"Like", " ", null, "to work", " ", "with Java", "!"};
        System.out.println(Joiner.on("").skipNulls().join(str_my));
        System.out.println();
    }
}
